# Generated by Django 2.0.7 on 2018-07-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TinyUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longUrl', models.CharField(max_length=20000)),
                ('shortUrl', models.CharField(max_length=20000)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('expiryDate', models.DateTimeField(verbose_name='expiryDate')),
                ('private', models.BooleanField()),
            ],
        ),
    ]
